# Generated by Django 4.2.3 on 2023-07-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_sending_the_newsletter', models.TimeField(verbose_name='time of sending the newsletter')),
                ('interval', models.CharField(choices=[('D', 'D'), ('W', 'W')], default='D', max_length=1)),
                ('newsletter_status', models.CharField(choices=[('completed', 'completed'), ('created', 'created'), ('launched', 'launched')], default='created', max_length=10)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ('time_of_sending_the_newsletter',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_title', models.CharField(max_length=250, verbose_name='message title')),
                ('message_content', models.TextField(max_length=150, verbose_name='message content')),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='m_a_s.newsletter')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('message_title',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterLogs',
            fields=[
                ('datatime_of_last_try', models.DateTimeField(verbose_name='datatime of last try')),
                ('status_of_try', models.BooleanField(verbose_name='status of try')),
                ('response_of_mail_server', models.BooleanField(verbose_name='response of mail server')),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='m_a_s.newsletter')),
            ],
            options={
                'verbose_name': 'newsletter logs',
                'verbose_name_plural': 'newsletters logs',
                'ordering': ('datatime_of_last_try',),
            },
        ),
        migrations.CreateModel(
            name='ClientOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, unique=True, verbose_name='contact email')),
                ('last_first_middle_name', models.CharField(max_length=150, verbose_name='full name')),
                ('comment', models.TextField(max_length=500, verbose_name='comment')),
                ('newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_a_s.newsletter', verbose_name='newsletter id')),
            ],
            options={
                'verbose_name': 'client of service',
                'verbose_name_plural': 'clients of service',
                'ordering': ('contact_email',),
            },
        ),
    ]
