# Generated by Django 4.2.3 on 2023-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_s', '0002_newsletter_newsletter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientofservice',
            name='comment',
            field=models.TextField(max_length=5000, verbose_name='comment'),
        ),
    ]
