# Generated by Django 4.2.3 on 2023-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_s', '0003_alter_clientofservice_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(max_length=5000, verbose_name='message content'),
        ),
    ]
