# Generated by Django 4.2.3 on 2023-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_s', '0004_alter_message_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientofservice',
            name='newsletter_id',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='m_a_s.clientofservice', verbose_name='clients'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='interval',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY')], default='DAILY', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_status',
            field=models.CharField(choices=[('completed', 'completed'), ('created', 'created'), ('launched', 'launched')], default='created', max_length=100),
        ),
    ]
