# Generated by Django 4.2.3 on 2023-08-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_a_s', '0007_alter_clientofservice_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterlogs',
            name='is_relevant',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='relevant status'),
        ),
        migrations.AddField(
            model_name='newsletterlogs',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
