# Generated by Django 4.2.3 on 2023-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('content', models.CharField(max_length=5000, verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='preview')),
                ('count_of_views', models.PositiveIntegerField(default=0, editable=False, verbose_name='count of views')),
                ('date_of_publish', models.DateField(auto_now_add=True, verbose_name='date of creation')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ('title',),
            },
        ),
    ]
